spring.application.name=contact-api
spring.datasource.url=jdbc:mysql://localhost:3306/contact_api_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=PWom.1729
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=*
